#+TITLE:  /Ubuntu/ 搭建 /gitlab/ 及 /Jenkins/ 纪录
* /Let's Encrypt/
** 安装客户端
#+BEGIN_SRC shell
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get -y update
sudo apt-get install -y certbot
#+END_SRC
** 申请证书
#+BEGIN_SRC shell
certbot --agree-tos --email email@example.com certonly --webroot -w /opt/gitlab/embedded/service/gitlab-rails/public/ -d www.example.com
#+END_SRC

上述命令中：
 + --agree-tos
   同意用户协议。
 + --email
   首次申请证书时，需要邮箱地址来创建 Let's Encrypt 的账号。不过，并不会验证此账号。
邮箱地址用于接受证书过期提醒。
 + certonly
   只申请证书。
 + --webroot
   通过在当前运行的 web 服务器下存放验证文件来验证身份。
 + -w
   指定当前运行的 web 服务器的根目录。

对于通过 Omnibus 安装的 GitLab 的默认的 nginx 服务器的根目录位于 /opt/gitlab/embedded/service/gitlab-rails/public/。
 + -d
   指定要申请证书的域名。
* /Gitlib/
** 安装
*** 安装必要的组件
#+BEGIN_SRC shell
sudo apt-get install -y curl openssh-server ca-certificates postfix
#+END_SRC
*** 安装源
#+BEGIN_SRC shell
curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
#+END_SRC
这里必须要吐槽一下， /gitlab/ 官方默认的安装指导是安装企业版 /gitlab-ee/ ，我们这里要安装的是开源版本 /gitlab-ce/ ，大家在安装
的时候要注意一下。
*** 安装包
#+BEGIN_SRC shell
sudo EXTERNAL_URL="https://gitlab.example.com" apt-get install gitlab-ce
#+END_SRC
** 与 /Let's Encrypt/ 集成
*** 配置文件
修改 ~/etc/gitlab/gitlab.rb~ 文件

#+BEGIN_SRC shell
letsencrypt['enable'] = true                      # GitLab 10.5 and 10.6 require this option
external_url "https://gitlab.example.com"         # Must use https protocol
letsencrypt['contact_emails'] = ['foo@email.com'] # Optional
#+END_SRC

*** 自动更新
#+BEGIN_SRC shell
letsencrypt['auto_renew'] = true
#+END_SRC

*** 启动新配置
#+BEGIN_SRC shell
sudo gitlab-ctl reconfigure
#+END_SRC
** 数据存放
一般情况是要给 /gitlab/ 单独挂载一个数据盘用来存放代码数据的。
*** 修改默认数据存放目录配置
/Gitlab/ 默然安装时，默认的仓库存储路径在 ~/var/opt/gitlab/git-data~ 目录下，仓库存储在子目录 /repositories/ 里面，可以通过修改
~/etc/gitlab/gitlab.rb~ 文件中 /git_data_dirs/ 参数来自定义父目录
#+begin_src shell
 git_data_dirs({
   "default" => {
     "path" => "/data0/gitlab/git-data"
    }
 })
#+end_src
我这里是把数据盘挂在 ~/data0~ 下面。

*注意 ：目标路径和其子路径必须不能为软链接。*
*** 生效配置
+ 没有数据
#+begin_src shell
# 停服
gitlab-ctl stop

# 重新配置服务
gitlab-ctl reconfigure
#+end_src
+ 已存在数据
#+begin_src shell
# 停服
gitlab-ctl stop

# 注意 'repositories'后面不带斜杠，而 '/data0/gitlab/git-data'后面是有斜杠的
rsync -av /var/opt/gitlab/git-data/repositories /data0/gitlab/git-data/

gitlab-ctl reconfigure

# 开启服务
gitlab-ctl start
#+end_src
*** 数据备份
+ 修改备份目录
#+begin_src shell
gitlab_rails['manage_backup_path'] = true
gitlab_rails['backup_path'] = "/data0/gitlab/backups"
#+end_src
+ 生效配置
#+begin_src shell
gitlab-ctl reconfigure

gitlab-ctl restart
#+end_src
+ 创建备份
#+begin_src shell
gitlab-rake gitlab:backup:create
#+end_src
如果成功的话，在 ~/data0/gitlab/backups~ 目录下会生成 /1593744116_2020_07_03_13.1.1_gitlab_backup.tar/ 这么格式的一个文件
（时间戳+日期+版本号）。
*** 恢复备份
#+begin_src shell
# 从指定时间戳的备份恢复（backups目录下有多个备份文件时）
gitlab-rake gitlab:backup:restore BACKUP=1593744116

# 从默认备份恢复（backups目录下只有一个备份文件时）
gitlab-rake gitlab:backup:restore
#+end_src
** 报错相关
*** /gitlab/ 点击 /admin area/ 的任何设定时报错 /500 Whoops,something went wrong on our end./
用管理员操作 /admin area/ 的 /setting/ 才会出现，一般用户没有影响。

解决如下：

首先 ~sudo gitlab-rails c~ 进入 ~gitalab~ 的控制台，然后依次执行下面两条指令:
#+begin_src shel
settings = ApplicationSetting.last
settings.update_column(:runners_registration_token_encrypted, nil)
#+end_src
最后重启即可。
#+begin_src shell
gitlab-ctl restart
#+end_src
* /Jenkins/
** 安装
#+BEGIN_SRC shell
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
# jenkins目前只支持java8和java11,在2.164版本之后支持java11
sudo apt install openjdk-11-jdk
sudo apt-get install -y jenkins
#+END_SRC
** 使用 /Openresty/ 作为代理
如果仅仅使用 /proxy_pass/ 反向代理 /jenkins/ 的 ~8080~ 端口，会有一些问题，所以还需要做一些简单的配置。我的配置如下：
#+begin_src nginx
upstream jenkins {
    keepalive 32; # keepalive connections
    server 127.0.0.1:8080; # jenkins ip and port
}

server {
    listen          80;       # Listen on port 80 for IPv4 requests

    #server_name     jenkins.example.com;

    #this is the jenkins web root directory (mentioned in the /etc/default/jenkins file)
    root            /var/cache/jenkins/war/;

    #access_log      /var/log/nginx/jenkins/access.log;
    #error_log       /var/log/nginx/jenkins/error.log;
    ignore_invalid_headers off; #pass through headers from Jenkins which are considered invalid by Nginx server.

    location ~ "^/static/[0-9a-fA-F]{8}\/(.*)$" {
        #rewrite all static files into requests to the root
        #E.g /static/12345678/css/something.css will become /css/something.css
        rewrite "^/static/[0-9a-fA-F]{8}\/(.*)" /$1 last;
    }

    location /userContent {
        #have nginx handle all the static requests to the userContent folder files
        #note : This is the $JENKINS_HOME dir
        root /var/lib/jenkins/;
        if (!-f $request_filename){
        #this file does not exist, might be a directory or a /**view** url
        rewrite (.*) /$1 last;
        break;
        }
        sendfile on;
    }

    location / {
        sendfile off;
        proxy_pass         http://jenkins;
        proxy_redirect     default;
        proxy_http_version 1.1;

        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_max_temp_file_size 0;

        #this is the maximum upload size
        client_max_body_size       10m;
        client_body_buffer_size    128k;

        proxy_connect_timeout      90;
        proxy_send_timeout         90;
        proxy_read_timeout         90;
        proxy_buffering            off;
        proxy_request_buffering    off; # Required for HTTP CLI commands in Jenkins > 2.54
        proxy_set_header Connection ""; # Clear for keepalive
    }
}
#+end_src
*这里要注意一下* : 如果打开系统管理页面报一个 ~It appears that your reverse proxy set up is broken.~ 的错误，那需要在系统配置
项里把 /Jenkins URL/ 改成 /http://ip:80/ 即指向服务器的80端口。
* 文档
+ [[https://about.gitlab.com/install/#ubuntu?version=ce][Download and install GitLab | GitLab]]
+ [[https://www.jenkins.io/doc/book/installing/#debianubuntu][Installing Jenkins]]
+ [[https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx][Certbot - Ubuntubionic Nginx]]
