#+TITLE: 中国哲学序言

* 概论
儒家入世，道家隐世，佛家出世；也常说，儒家修身齐家治国平天下，道家反者道之动，弱者道之用，佛家缘起性空。

儒家文化——积极进取的文化

儒家倡导知识的获取和品德的培养，是一种积极向上的文化。

道家文化——遵循规律的文化

道家遵循自然规律，提倡无为而治，顺其自然，是一种尊重自然，尊重规律的文化。

佛家文化——无私奉献的文化

佛家思想中蕴含了慈悲和福报论，是一种无私奉献的文化。

* 做人标准

儒家文化——仁、义、礼、智、信、恕、忠、孝、悌

儒家对于做人标准要求很高，共九点。仁是仁爱，是儒家思想的核心。义原指"宜"，即行为适合于"礼"。礼是孔子及儒家的政治与伦理范畴。智同"知"，是孔子的认识论和伦理学的基本范畴。信：指待人处事的诚实不欺，言行一致的态度。
恕是指宽恕，己所不欲勿施于人。忠是指与人交往中的老实忠厚。孝是对父母的尊重。悌是对兄长的敬爱。

道家文化——领悟道法，淡泊名利

“道”是道家文化的核心，道家创始人老子认为道是世界本源，天地万物都有道而生，同时道也是存在于万物之中的普遍法则。两个互相矛盾的对立面以及对立面的相互转化都是由道完成的，只有领悟了“道”，才能更好的顺应自然。
另外，“以其不争，故天下莫能与之争。”也是利用了转化思想完成的，淡泊名利，不争也是争。

佛家文化——诸恶莫做、众善奉行

佛家文化中，因果轮回观深入人心。做善事有善报，干坏事便要尝坏果。所以佛家倡导信徒慈悲为怀，多积善果。

* 人生观

儒家文化——积极进取、建功立业

《论语·为政》中有言：“吾十有五，而志于学。三十而立。四十而不惑。五十而知天命。六十而耳顺。七十而从心所欲，不逾矩。”这句话就是对儒家人生观的最佳阐释，人三十当立，该当建功立业。

道家文化——顺其自然、自我完善

道家的顺其自然观念就是要掌握道的法度，与自然和谐相处。这绝非简单容易之事，想要掌握道的规律就需要多思考观察和学习，自我完善。

佛家文化——慈爱众生、无私奉献

佛家文化中有业报观，讲求对世间万物都报以同等的慈悲，无私奉献，超凡脱俗。

* 世界观

儒家文化——世界是展现才华的舞台

儒家文化重视人才，鼓励人们追求知识。孔子创办私学，主张有教无类也是为了给有思想有才华的人提供知识基础，让他们更好地展现自己的才华。

道家文化——大自然是人类赖以生存的环境，重视自然界规律

道家顺其自然和无为而治的思想很大一部分就是仰仗着自然界自身所拥有的一套平衡系统，所以要重视自然界的各种规律。

佛家文化——相由心生，心中即世界

佛家文化偏向于唯心主义，相由心生，所以佛教强调心灵的纯净，只要心灵纯净，那么所看到的世界也就变得纯净。

* 价值观

儒家文化——不断提升自己实现人生价值

我们创造物质财富额精神财富的过程同时也是在实现自身价值的过程，儒家倡导提升自己的才能和道德都是为了更好的实现自身价值做服务的。

道家文化——以自身的完善促进社会的和谐

道家在治国思想上的无为而治是一个较为理想化的治国方式，所以这就对人民的素质提出了很大的要求，注重自身的完善，才能更好的促进社会的和谐。

佛家文化——在为他人献爱心的过程中实现人生价值

为他人献爱心、做好事是主张慈悲为怀的佛家最提倡的，在献爱心的过程中，人们的精神和灵魂都会得到升华，获得真正的快乐，实现自己的人生价值。

* 哲学倾向

儒家文化——入世哲学

儒家文化是三家最贴近我们生活的一种文化，追求知识，培养道德，积极向上等等，都让我们“入世”，让我们更好地适应社会和生活。

道家文化——出世哲学

道家的很多思想都是偏理想化的生活，超脱凡尘俗世，不计较得失，顺其自然，淡泊名利，这些都是能让心灵沉静的思想。

佛家文化——以出世的思想，做入世的事业

佛家文化具有超逸的处事态度和无私奉献的精神境界，可以说是有了超脱凡世的思想。佛家又倡导入凡世做好事，帮助他人。

* 物质食粮对精神食粮的比喻

儒家文化——主食，不吃就会饿

儒家文化适合当做自己主要遵循的信念，他贴近生活，只要努力和坚持就能够达到。按照儒家思想去行动后，你能有效感受到思想给自己带来的提升和帮助。

道家文化——副食，不吃没滋味

道家文化适合取里面一些观念遵循，要完全掌握道家文化十分困难，顺其自然对于改善自己的心态有很大的好处，能有效增添生活中的幸福指数。

佛家文化——水果，不吃不甜蜜

佛家文化想要完全学习也很困难，可以学习其中的精神，不惧于奉献，乐得奉献，才能让自己的生活更甜蜜。
