#+TITLE: 经济学基本概念
* 货币供应量
** 说明
在经济学中，货币供应量是指在某一个特定时间点中，货币资产的总量。
** 定义
- M0 = 流通中的现金
- M1 = M0 + 商业银行活期存款，称为狭义货币供应量。
- M2 = M1 + 商业银行定期存款，称为广义货币供应量。
** 中华人民共和国
- M0 流通中的现金 = 流通中现金
- M1 货币 = M0＋可开支票进行支付的单位活期存款
- M2 货币和准货币 = M1＋居民储蓄存款＋单位定期存款＋单位其他存款＋证券公司客户保证金
** 通货膨胀
通货膨胀，意指一般物价水平在某一时期内，连续性地以相当的幅度上涨的状态
** 通货紧缩
通货紧缩（英语：deflation，又称通缩），意指整体物价水平下降。
** 停滞性通货膨胀
停滞性通货膨胀（英文：stagflation），简称滞胀或停滞性通胀，在经济学、特别是宏观经济学中，特指经济停滞（stagnation），失业及通货膨胀（inflation）同时持续高涨的经济现象。
通俗的说就是指物价上升，但经济停滞不前。它是通货膨胀长期发展的结果。
* 物价指数
** 说明
物价指数是一个衡量市场上物价总水平变动情况的指数。物价总水平上升则意味着发生了通货膨胀，反之，物价总水平下降意味着通货紧缩，物价指数正是用来衡量经济中发生的通货膨胀或是通货紧缩的一个指标。
如果物价指数上升过大则表明通货膨胀已成为了影响社会和经济不稳定的一个因素，央行就会有紧缩货币的政策和相关财政政策的颁布，对社会经济的发展有一定的影响。所以该指数的升高往往会对经济造成影响。
物价指数是一种能够表示一个经济的宏观经济指标。
** 居民消费价格指
居民消费价格指数（英语：Consumer Price Index，缩写：CPI），在经济学上，是反映与居民生活有关的产品及劳务价格统计出来的物价变动指标，以百分比变化为表达形式。它是衡量通货膨胀的主要指
标之一。一般定义超过3％为通货膨胀，超过5％就是比较严重的通货膨胀。CPI往往是市场经济活动与政府货币政策的一个重要参考指标。CPI稳定、就业充分及GDP增长往往是最重要的社会经济目标。
如果消费者物价指数升幅过大，表明通胀已经成为经济不稳定因素，国家会有紧缩货币政策和财政政策的风险，从而造成经济前景不明朗。因此，该指数过高的升幅往往不被市场欢迎。可用的手段有加息、紧缩
银根、采取稳健的财政政策、增加生产、平抑物价等。
** 生产物价指数
生产物价指数（Producer Price Index，简称PPI）是一个用来衡量制造商出厂价的平均变化的指数，它是统计部门收集和整理的若干个物价指数中的一个。如果生产物价指数比预期数值高时，表明有通货
膨胀的风险。如果生产物价指数比预期数值低时，则表明有通货紧缩的风险。
** 平均物价指数
平均物价指数(英语：GDP deflator)，又译GDP平减物价指数、国内生产总值平均物价指数,是名义GDP(Nominal GDP)与真实GDP(Real GDP)的比率，反映了通胀率的大小，
表达了货币供给量与货币需求的比例关系。
** 趸售物价指数
趸售物价指数（Wholesale Price Index）简称WPI，是批发货品中代表性商品的价格所形成的物价指数。
